image: ubuntu:latest

# Define global variables
variables:
  ENVIRONMENT: "staging"
  WORKFLOW_REPO_URL: "https://$GITHUB_PAT@github.com/stack-spot/workflow-stackspot-actions-runtime-selfhosted.git"

stages:
  - run_stackspot

# Common setup steps for all jobs
before_script:
  # Install necessary dependencies
  - apt-get -qq update
  - apt-get install -y curl git

  # Download and install STK CLI
  - curl -s -O "https://stk.stackspot.com/installer/linux/stk"
  - chmod +x stk
  - ./stk init
  
  - export STK=~/.stk/bin/stk

  # Verify STK CLI installation
  - $STK --version

stk:
  stage: run_stackspot
  script:
    # Export environment variables for StackSpot
    - export INPUTS_CLIENT_ID=$STK_CLIENT_ID
    - export INPUTS_CLIENT_KEY=$STK_CLIENT_SECRET
    - export INPUTS_CLIENT_REALM=$STK_REALM
    - export INPUTS_TF_STATE_REGION=$AWS_REGION
    - export INPUTS_IAC_REGION=$AWS_REGION
    - export INPUTS_AWS_REGION=$AWS_REGION
    - export INPUTS_IAC_BUCKET_NAME=$IAC_BUCKET_NAME
    - export INPUTS_TF_STATE_BUCKET_NAME=$TF_STATE_BUCKET_NAME
    - export INPUTS_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export INPUTS_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export INPUTS_AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
    - export INPUTS_ENVIRONMENT=$ENVIRONMENT

    # Authenticate with StackSpot
    - $STK login --client-id $INPUTS_CLIENT_ID --client-key $INPUTS_CLIENT_KEY --realm $INPUTS_CLIENT_REALM

    # Use the specified workspace
    - $STK use workspace $STK_WORKSPACE

    # Clone the workflow repository
    - git clone $WORKFLOW_REPO_URL
    - cd workflow-stackspot-actions-runtime-selfhosted
    - run_action_path=$(pwd)
    - cd ..

    # Run the StackSpot action
    - $STK run action $run_action_path --workflow_type deploy --version_tag $CI_JOB_ID --repository_name $CI_PROJECT_NAME --non-interactive
