schema-version: v3
kind: action
metadata:
  name: runtime-manager-action
  display-name: runtime-manager-action
  description: runtime-manager-action
  version: 0.0.1
spec:
  type: python
  docs:
    en-us: docs/en-us/docs.md
  repository: https://github.com/stack-spot/workflow-stackspot-actions-runtime-selfhosted.git
  inputs:

    - label: Bucket to save generated tfstate files
      name: tf_state_bucket_name
      type: text
      required: true
      help: 'Inform bucket to save generated tfstate files'

    - label: Region configuration for tfstate
      name: tf_state_region
      type: text
      required: true
      help: 'Inform region configuration for tfstate'

    - label: Bucket to save generated iac files
      name: iac_bucket_name
      type: text
      required: true
      help: 'Inform bucket to save generated iac files'

    - label: Region configuration for iac
      name: iac_region
      type: text
      required: true
      help: 'Inform region configuration for iac'

    - label: Verbose configuration
      name: verbose
      type: bool
      required: false
      help: 'verbose configuration'

    - label: Path to the directory where the .stk is located.
      name: workdir
      type: text
      required: false
      help: 'Inform path to the directory where the .stk is located.'

  python:
    workdir: .
    script: script.py
