schema-version: v3
kind: action
metadata:
  name: runtime-cancel-run-action
  display-name: runtime-cancel-run-action
  description: runtime-cancel-run-action
  version: 0.0.1
spec:
  type: python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  repository: https://github.com/stack-spot/workflow-stackspot-actions-runtime-selfhosted.git
  inputs:
    - label: Run id
      name: run_id
      type: text
      required: false
      help: 'Inform execution Id'
    - label: Force Cancel
      name: force_cancel
      type: bool 
      default: false
      required: false
      help: 'Force cancel?'
  python:
    workdir: .
    script: script.py
