schema-version: v3
kind: action
metadata:
  name: runtime-iac-action
  display-name: runtime-iac-action
  description: runtime-iac-action
  version: 0.0.1
spec:
  type: shell
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  repository: https://github.com/stack-spot/workflow-stackspot-actions-runtime-selfhosted.git
  inputs:
    - label: "Features Log Level"
      name: features_level_log
      type: text
      required: true
    - label: "CLIENT ID"
      name: client_id
      type: text
      required: true
    - label: "CLIENT KEY"
      name: client_key
      type: text
      required: true
    - label: "CLIENT REALM"
      name: client_realm
      type: text
      required: true
    - label: "Git Repository Name"
      name: repository_name
      type: text
      required: true
    - label: "AWS ACCESS KEY ID from console"
      name: aws_access_key_id
      type: text
      required: true
    - label: "AWS SECRET ACCESS KEY from console"
      name: aws_secret_access_key
      type: text
      required: true
    - label: "AWS SESSION TOKEN from console"
      name: aws_session_token
      type: text
      required: true
    - label: "AWS REGION"
      name: aws_region
      type: text
      required: true
    - label: "AWS ROLE ARN"
      name: aws_role_arn
      type: text
      required: false
    - label: "Runtime Run Task Id"
      name: run_task_id
      type: text
      required: true
    - label: "Deploy Container url"
      name: container_url
      type: text
      default: "stackspot/runtime-job-iac:latest"
      required: false
    - label: "Path to mount inside the docker"
      name: path_to_mount
      type: text
      default: "{{ github.workspace }} ??"
      required: true
    - label: "Base Path Output"
      name: base_path_output
      type: text
      default: "."
      required: false
    - label: "Whether or not checkout is enabled."
      name: CHECKOUT_BRANCH
      type: bool
      default: false
      required: false
  shell:
    workdir: .
    
    script:
      linux: |
        chmod +x {{component_path}}/script.sh
        sh {{component_path}}/script.sh
      mac: |
        chmod +x {{component_path}}/script.sh
        sh {{component_path}}/script.sh
      windows: |