schema-version: v3
kind: action
metadata:
  name: runtime-create-manifest-action
  display-name: runtime-create-manifest-action
  description: runtime-create-manifest-action
  version: 0.0.1
spec:
  type: python
  docs:
    en-us: docs/en-us/docs.md
  repository: https://github.com/stack-spot/workflow-stackspot-actions-runtime-selfhosted.git
  inputs:
    - label: Environment used to deploy
      name: environment
      type: text
      required: true
      help: 'Inform environment used to deploy'

    - label: Deploy version tag
      name: version_tag
      type: text
      required: true
      help: 'Inform deploy version tag'

    - label: Path to API file to publish on StackSpot Catalog API
      name: open_api_path
      type: text
      required: false
      help: 'Inform path to API file to publish on StackSpot Catalog API'

    - label: Dynamic Inputs
      name: dynamic_inputs
      type: text
      required: false
      help: '--key1 value1 --key2 value2'

  python:
    workdir: .
    script: script.py
    
      

