schema-version: v3
kind: action
metadata:
  name: runtime-create-manifest-action
  display-name: runtime-create-manifest-action
  description: runtime-create-manifest-action
  version: 0.0.1
spec:
  type: shell
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  repository: https://github.com/stack-spot/workflow-stackspot-actions-runtime-selfhosted.git
  inputs:
    - label: Environment used to deploy
      name: environment
      type: text
      required: true
      help: 'Inform environment used to deploy'

    - label: Workspace used to deploy
      name: workspace
      type: text
      required: true
      help: 'Inform workspace used to deploy'

    - label: Deploy version tag
      name: version_tag
      type: text
      required: true
      help: 'Inform deploy version tag'

    - label: Branch to perform checkout in Runtime
      name: branch
      type: text
      required: false
      help: 'Inform branch to perform checkout in Runtime'

    - label: Path to API file to publish on StackSpot Catalog API
      name: open_api_path
      type: text
      required: false
      help: 'Inform path to API file to publish on StackSpot Catalog API'

    - label: Dynamic Inputs
      name: dynamic_inputs
      type: text
      required: false
      help: '--key1 value1 --key2 value2'

    - label: Verbose configuration
      name: verbose
      type: bool
      required: false
      default: true
      help: 'verbose configuration'

  shell:
    workdir: .
    
    script:
      linux: |
        chmod +x {{component_path}}/script.sh
        sh {{component_path}}/script.sh
      mac: |
        chmod +x {{component_path}}/script.sh
        sh {{component_path}}/script.sh
      windows: |
        echo "Not supported"
      

